### ISSUE TITLE
About data split for IXI dataset

### ISSUE THREAD

**Issue by ShiverK** [eeeric-code/I3Net#1]
Thanks for your contribution. I noticed that in your experiments, you used 150 volumes for training and 35 volumes for testing from the IXI dataset. Could you please share the specific data split you used? Additionally, did you perform any specific preprocessing steps, such as registration or normalization, on the MR volumes before using them in your experiments

**Comment by eeeric-code** [comment]
Thank you for reminding me about the data preprocessing for MRI. IXI dataset has been collected at three different hospitals. We have only utilized the data from Hammersmith Hospital (HH), which includes 185 volumes. We split the data according to their names, using the first 150 (IXI012-HH-1211 ~ IXI546-HH-2450) for training and the remaining 35 (IXI556-HH-2452 ~ IXI661-HH-2788) for testing. We do not perform any specific preprocessing on the data, neither registration nor normalization.
